### ISSUE TITLE
Can't migrate at install time

### ISSUE THREAD

**Issue by jlecour** [Evolix/chexpire#66]
```
$ bundle exec rake db:migrate RAILS_ENV=development
== 20180523145630 DeviseCreateUsers: migrating ================================
-- create_table(:users)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'users' already exists: CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `email` varchar(255) DEFAULT '' NOT NULL, `encrypted_password` varchar(255) DEFAULT '' NOT NULL, `reset_password_token` varchar(255), `reset_password_sent_at` datetime, `remember_created_at` datetime, `sign_in_count` int DEFAULT 0 NOT NULL, `current_sign_in_at` datetime, `last_sign_in_at` datetime, `current_sign_in_ip` varchar(255), `last_sign_in_ip` varchar(255), `confirmation_token` varchar(255), `confirmed_at` datetime, `confirmation_sent_at` datetime, `unconfirmed_email` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL)
/localhome/jlecour/work/intra/chexpire/db/migrate/20180523145630_devise_create_users.rb:8:in `change'
/home/jlecour/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/jlecour/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'users' already exists: CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `email` varchar(255) DEFAULT '' NOT NULL, `encrypted_password` varchar(255) DEFAULT '' NOT NULL, `reset_password_token` varchar(255), `reset_password_sent_at` datetime, `remember_created_at` datetime, `sign_in_count` int DEFAULT 0 NOT NULL, `current_sign_in_at` datetime, `last_sign_in_at` datetime, `current_sign_in_ip` varchar(255), `last_sign_in_ip` varchar(255), `confirmation_token` varchar(255), `confirmed_at` datetime, `confirmation_sent_at` datetime, `unconfirmed_email` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL)
/localhome/jlecour/work/intra/chexpire/db/migrate/20180523145630_devise_create_users.rb:8:in `change'
/home/jlecour/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/jlecour/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'

Caused by:
Mysql2::Error: Table 'users' already exists
/localhome/jlecour/work/intra/chexpire/db/migrate/20180523145630_devise_create_users.rb:8:in `change'
/home/jlecour/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/jlecour/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by jlecour** [comment]
There is a complex issue which depends on the verison of MySQL/MariaDB.

Basically, if you use MySQL < 5.7 (MySQL 5.5 or MariaDB 10.1) the workaround is to force the server to create tables with "utf8" instead of "utf8mb4" : 

```
character-set-server=utf8
collation-server=utf8_general_ci
```
